# Generated by Django 4.2.7 on 2024-05-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_training_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
