# Generated by Django 4.2.7 on 2024-05-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_machinelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineList',
        ),
    ]
